# This workflow will build and push a new container image to DockerHub,
# a watchtower container listens on for the updates to the image so as to restart the local containers
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create a Docker hub repository to store your images.
#

on:
  push:
    branches:
      - staging

name: Deploy to Docker Hub for Staging

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: savarlite/images:backpocket-latest
          buildArgs: REPOSITORY=savarlite/images:backpocket-latest
          
